### ISSUE TITLE
Compiling a R package integrating a static library.

### ISSUE THREAD

**Issue by akhikolla** [molpopgen/devnotes#1]
Hello,

I am trying to integrate a static C++ library called deepstate with Rcpp package. Deepstate help me test the functions in the Rcpp package -- RcppDeepState/src/Testharness.cpp
 
Testharness.cpp has the code to test the functions in the RcppDeepState package and now  I am having trouble compiling the Rcpp package because I don't exactly understand how the script should look like to compile the package getting the functionalities from deepstate library.
what should the cppflags and ldflags look like

can you please help me with this. I referred to your article in wiki pages **Rcpp and compiler flags.**
that you tried linking run time libraries to R package what are the folders I should include and how should the Makevars file look like and where should it be located? 

Can you suggest a command line on how can I get the deepstate and Rcpp package to compile together?

**Comment by molpopgen** [comment]
Sorry to say I can't help here.  I have not used Rcpp in several years.  You'll have to look elsewhere and/or post to their mailing list.
